/**
 * TikTok Service & Audio/Speech Extraction Engine
 * ------------------------------------------------
 * Capabilities:
 *   - Unshortens & resolves TikTok redirect URLs (vm.tiktok.com, vt.tiktok.com, tiktok.com/t/...)
 *   - Extracts public video metadata (author, nickname, stats, music, description, tags)
 *   - Direct closed captions / subtitles extraction (Arabic, English, etc.) from internal JSON/DOM
 *   - Low-bitrate audio-only extraction fallback & Whisper-compatible speech pipeline
 *   - Intelligent AI context builder for OSINT, sentiment, and content summarization
 *   - In-memory cache with 30-minute TTL
 */

// ─── Types ────────────────────────────────────────────────────────────────────

export interface TikTokStats {
  likes: number;
  comments: number;
  shares: number;
  views: number;
  saves: number;
}

export interface TikTokAuthor {
  username: string;
  nickname: string;
  avatarUrl?: string;
  signature?: string;
  verified?: boolean;
}

export interface TikTokMusic {
  id?: string;
  title: string;
  authorName: string;
  playUrl?: string;
  coverUrl?: string;
  duration?: number;
}

export interface TikTokSubtitleTrack {
  lang: string;
  langCode: string;
  url: string;
  format: 'webvtt' | 'json' | 'srt';
  isAutoGenerated?: boolean;
}

export interface TikTokTranscriptSegment {
  text: string;
  startMs: number;
  endMs: number;
}

export interface TikTokResult {
  videoId: string;
  canonicalUrl: string;
  inputUrl: string;
  title: string;
  description: string;
  hashtags: string[];
  author: TikTokAuthor;
  stats: TikTokStats;
  music: TikTokMusic;
  thumbnailUrl: string;
  dynamicCover?: string;
  originCover?: string;
  playUrl?: string;
  subtitles: TikTokSubtitleTrack[];
  transcriptText?: string;
  transcriptSegments?: TikTokTranscriptSegment[];
  transcriptSource: 'closed_captions' | 'audio_whisper' | 'video_description';
  durationSeconds?: number;
  createTime?: number;
  fetchedAt: number;
  cached?: boolean;
}

export type TikTokError =
  | 'INVALID_URL'
  | 'VIDEO_UNAVAILABLE'
  | 'PRIVATE_VIDEO'
  | 'PARSE_ERROR'
  | 'NETWORK_ERROR';

export interface TikTokFailure {
  error: TikTokError;
  message: string;
  videoId?: string;
}

// ─── Cache (30 min TTL) ───────────────────────────────────────────────────────

const CACHE_TTL_MS = 30 * 60 * 1000;
interface CacheEntry { result: TikTokResult; expiresAt: number; }
const tiktokCache = new Map<string, CacheEntry>();

function getCached(key: string): TikTokResult | null {
  const entry = tiktokCache.get(key);
  if (!entry || Date.now() > entry.expiresAt) {
    tiktokCache.delete(key);
    return null;
  }
  return { ...entry.result, cached: true };
}

function setCached(key: string, result: TikTokResult): void {
  tiktokCache.set(key, { result, expiresAt: Date.now() + CACHE_TTL_MS });
}

// ─── URL Parsing & Unshortening ───────────────────────────────────────────────

export function isTikTokUrl(text: string): boolean {
  if (!text || typeof text !== 'string') return false;
  return /(?:tiktok\.com|vm\.tiktok\.com|vt\.tiktok\.com)\//i.test(text);
}

export function extractTikTokUrlFromText(text: string): string | null {
  if (!text) return null;
  const m = text.match(/https?:\/\/(?:(?:www|vm|vt|m|t)\.)?tiktok\.com\/[^\s<>"']+/i);
  if (m) return m[0];
  const s = text.match(/(?:^|\s)((?:vm|vt)\.tiktok\.com\/[^\s<>"']+)/i);
  if (s) return 'https://' + s[1].trim();
  return null;
}

export function extractTikTokVideoId(url: string): string | null {
  if (!url) return null;
  const directMatch = url.match(/\/video\/(\d{15,22})/i);
  if (directMatch) return directMatch[1];

  const vMatch = url.match(/\/v\/(\d{15,22})/i);
  if (vMatch) return vMatch[1];

  const itemMatch = url.match(/share_item_id=(\d{15,22})/i);
  if (itemMatch) return itemMatch[1];

  return null;
}

/** Follows HTTP redirects to unshorten vm.tiktok.com or vt.tiktok.com links using mobile client emulation */
export async function unshortenTikTokUrl(inputUrl: string): Promise<string> {
  let currentUrl = inputUrl.startsWith('http') ? inputUrl : `https://${inputUrl}`;
  let hops = 0;
  const maxHops = 6;

  while (hops < maxHops) {
    hops++;
    try {
      const controller = new AbortController();
      const timer = setTimeout(() => controller.abort(), 4500);

      const res = await fetch(currentUrl, {
        method: 'GET',
        redirect: 'manual',
        signal: controller.signal,
        headers: {
          'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1',
          'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
          'Accept-Language': 'ar,en;q=0.9',
        }
      });
      clearTimeout(timer);

      const loc = res.headers.get('location');
      if (res.status >= 300 && res.status < 400 && loc) {
        currentUrl = loc.startsWith('http') ? loc : new URL(loc, currentUrl).href;
        if (extractTikTokVideoId(currentUrl)) break;
      } else {
        break;
      }
    } catch {
      break;
    }
  }

  return currentUrl.split('?')[0];
}

// ─── Subtitle Downloader & Parser ─────────────────────────────────────────────

async function fetchAndParseSubtitles(trackUrl: string): Promise<{ text: string; segments: TikTokTranscriptSegment[] } | null> {
  try {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 5000);
    const res = await fetch(trackUrl, {
      signal: controller.signal,
      headers: {
        'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1',
        'Accept': '*/*',
      }
    });
    clearTimeout(timer);

    if (!res.ok) return null;
    const body = await res.text();
    const segments: TikTokTranscriptSegment[] = [];

    // JSON format subtitles
    if (body.trim().startsWith('{')) {
      try {
        const jsonData = JSON.parse(body);
        const utterances = jsonData?.utterances || jsonData?.body || [];
        for (const u of utterances) {
          const t = (u.text || u.words?.map((w: any) => w.word).join(' ') || '').trim();
          if (t) {
            segments.push({
              text: t,
              startMs: u.start_time || u.startTime || 0,
              endMs: u.end_time || u.endTime || 0,
            });
          }
        }
      } catch {}
    }

    // WebVTT / SRT format subtitles
    if (segments.length === 0 && (body.includes('WEBVTT') || body.includes('-->'))) {
      const vttRegex = /(?:(\d{2}):)?(\d{2}):(\d{2})[\.,](\d{3})\s*-->\s*(?:(\d{2}):)?(\d{2}):(\d{2})[\.,](\d{3})[^\n]*\n([\s\S]*?)(?=\n\s*(?:(?:\d{2}:)?\d{2}:\d{2}[\.,]\d{3}|\d+|$))/g;
      let m: RegExpExecArray | null;
      while ((m = vttRegex.exec(body)) !== null) {
        const h1 = m[1] ? parseInt(m[1].replace(':', ''), 10) : 0;
        const m1 = parseInt(m[2], 10);
        const s1 = parseInt(m[3], 10);
        const ms1 = parseInt(m[4], 10);
        const startMs = (h1 * 3600 + m1 * 60 + s1) * 1000 + ms1;

        const h2 = m[5] ? parseInt(m[5].replace(':', ''), 10) : 0;
        const m2 = parseInt(m[6], 10);
        const s2 = parseInt(m[7], 10);
        const ms2 = parseInt(m[8], 10);
        const endMs = (h2 * 3600 + m2 * 60 + s2) * 1000 + ms2;

        const rawText = m[9].replace(/<[^>]+>/g, '').replace(/&amp;/g, '&').replace(/&#39;/g, "'").trim();
        if (rawText) {
          segments.push({
            text: rawText,
            startMs,
            endMs,
          });
        }
      }
    }

    if (segments.length > 0) {
      const text = segments.map(s => s.text).join(' ').replace(/\s{2,}/g, ' ').trim();
      return { text, segments };
    }

    return null;
  } catch {
    return null;
  }
}

// ─── oEmbed Fallback ──────────────────────────────────────────────────────────

async function fetchTikTokOEmbed(canonicalUrl: string): Promise<{ title?: string; author_name?: string; thumbnail_url?: string } | null> {
  try {
    const oembedUrl = `https://www.tiktok.com/oembed?url=${encodeURIComponent(canonicalUrl)}`;
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 4000);
    const res = await fetch(oembedUrl, { signal: controller.signal });
    clearTimeout(timer);

    if (res.ok) {
      return await res.json();
    }
    return null;
  } catch {
    return null;
  }
}

async function fetchTikWMData(url: string): Promise<any | null> {
  try {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 6000);
    const apiUrl = `https://www.tikwm.com/api/?url=${encodeURIComponent(url)}`;
    const res = await fetch(apiUrl, {
      signal: controller.signal,
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36',
        'Accept': 'application/json, text/plain, */*',
      }
    });
    clearTimeout(timer);
    if (!res.ok) return null;
    const json = await res.json();
    if (json && json.code === 0 && json.data) {
      return json.data;
    }
    return null;
  } catch {
    return null;
  }
}

// ─── Master Pipeline: fetchTikTokData ─────────────────────────────────────────

export async function fetchTikTokData(input: string): Promise<TikTokResult | TikTokFailure> {
  if (!input || typeof input !== 'string') {
    return { error: 'INVALID_URL', message: 'رابط تيك توك غير صالح أو فارغ.' };
  }

  const [tikwmFastData, canonicalUrl] = await Promise.all([
    fetchTikWMData(input.trim()),
    unshortenTikTokUrl(input.trim())
  ]);

  const effectiveUrl = (canonicalUrl && canonicalUrl.includes('/video/')) ? canonicalUrl : input.trim();
  const videoId = (tikwmFastData && tikwmFastData.id) ? String(tikwmFastData.id) : (extractTikTokVideoId(effectiveUrl) || extractTikTokVideoId(input) || 'unknown');

  const cached = getCached(effectiveUrl) || getCached(videoId);
  if (cached) {
    console.log(`[TikTokService] Cache hit for videoId: ${videoId}`);
    return cached;
  }

  console.log(`[TikTokService] Fetching metadata for: ${effectiveUrl} (ID: ${videoId})`);

  try {
    const [pageRes, oembedData, tikwmRetryData] = await Promise.all([
      (async () => {
        const controller = new AbortController();
        const timer = setTimeout(() => controller.abort(), 6000);
        try {
          const res = await fetch(input.trim().startsWith('http') ? input.trim() : `https://${input.trim()}`, {
            signal: controller.signal,
            headers: {
              'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1',
              'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
              'Accept-Language': 'ar,en-US;q=0.9,en;q=0.8',
            }
          });
          clearTimeout(timer);
          if (res.ok) return await res.text();
          return '';
        } catch {
          return '';
        }
      })(),
      fetchTikTokOEmbed(effectiveUrl),
      tikwmFastData ? Promise.resolve(tikwmFastData) : fetchTikWMData(effectiveUrl)
    ]);

    const tikwm = tikwmFastData || tikwmRetryData;
    let itemStruct: any = null;

    if (pageRes) {
      const uMatch = pageRes.match(/<script\s+id="__UNIVERSAL_DATA_FOR_REHYDRATION__"[^>]*>([\s\S]*?)<\/script>/);
      if (uMatch) {
        try {
          const uData = JSON.parse(uMatch[1]);
          const scope = uData?.__DEFAULT_SCOPE__ || {};
          itemStruct =
            scope['webapp.reflow.video.detail']?.itemInfo?.itemStruct ||
            scope['webapp.video-detail']?.itemInfo?.itemStruct ||
            scope['webapp.video-detail.reflow']?.itemInfo?.itemStruct ||
            scope['webapp.video.detail']?.itemInfo?.itemStruct;
        } catch {}
      }

      if (!itemStruct) {
        const sigiMatch = pageRes.match(/<script\s+id="SIGI_STATE"[^>]*>([\s\S]*?)<\/script>/);
        if (sigiMatch) {
          try {
            const sigiData = JSON.parse(sigiMatch[1]);
            const itemModule = sigiData?.ItemModule || {};
            itemStruct = Object.values(itemModule)[0];
          } catch {}
        }
      }
    }

    const desc = (itemStruct?.desc || tikwm?.title || oembedData?.title || '').trim();
    const hashtagMatches = desc.match(/#[\w\u0600-\u06FF]+/g) || [];
    const hashtags: string[] = Array.from(new Set(hashtagMatches));

    const author: TikTokAuthor = {
      username: itemStruct?.author?.uniqueId || tikwm?.author?.unique_id || oembedData?.author_name || 'TikTok User',
      nickname: itemStruct?.author?.nickname || tikwm?.author?.nickname || oembedData?.author_name || 'TikTok User',
      avatarUrl: itemStruct?.author?.avatarLarger || itemStruct?.author?.avatarThumb || tikwm?.author?.avatar,
      signature: itemStruct?.author?.signature || tikwm?.author?.signature,
      verified: Boolean(itemStruct?.author?.verified ?? tikwm?.author?.verified),
    };

    const stats: TikTokStats = {
      likes: Number(itemStruct?.stats?.diggCount || itemStruct?.statsV2?.diggCount || tikwm?.digg_count || 0),
      comments: Number(itemStruct?.stats?.commentCount || itemStruct?.statsV2?.commentCount || tikwm?.comment_count || 0),
      shares: Number(itemStruct?.stats?.shareCount || itemStruct?.statsV2?.shareCount || tikwm?.share_count || 0),
      views: Number(itemStruct?.stats?.playCount || itemStruct?.statsV2?.playCount || tikwm?.play_count || 0),
      saves: Number(itemStruct?.stats?.collectCount || itemStruct?.statsV2?.collectCount || tikwm?.collect_count || 0),
    };

    const music: TikTokMusic = {
      id: itemStruct?.music?.id || tikwm?.music_info?.id,
      title: itemStruct?.music?.title || tikwm?.music_info?.title || tikwm?.music || 'Original Sound',
      authorName: itemStruct?.music?.authorName || tikwm?.music_info?.author || author.nickname,
      playUrl: itemStruct?.music?.playUrl || tikwm?.music,
      coverUrl: itemStruct?.music?.coverLarge || itemStruct?.music?.coverThumb || tikwm?.music_info?.cover,
      duration: itemStruct?.music?.duration || tikwm?.music_info?.duration,
    };

    const thumbnailUrl =
      itemStruct?.video?.cover ||
      itemStruct?.video?.originCover ||
      itemStruct?.video?.dynamicCover ||
      tikwm?.cover ||
      tikwm?.origin_cover ||
      oembedData?.thumbnail_url ||
      'https://www.tiktok.com/favicon.ico';

    const dynamicCover = itemStruct?.video?.dynamicCover || tikwm?.dynamic_cover;
    const originCover = itemStruct?.video?.originCover || tikwm?.origin_cover;
    const playUrl = itemStruct?.video?.playAddr || tikwm?.play;

    const subtitleInfos: any[] = itemStruct?.video?.subtitleInfos || itemStruct?.contents || [];
    const subtitles: TikTokSubtitleTrack[] = [];

    for (const sub of subtitleInfos) {
      if (sub.Url) {
        subtitles.push({
          lang: sub.LanguageCodeName || sub.LanguageID || 'unknown',
          langCode: sub.LanguageID || 'und',
          url: sub.Url,
          format: (sub.Format || 'webvtt').toLowerCase() as any,
          isAutoGenerated: Boolean(sub.Source === 'ASR' || sub.Version?.includes('whisper')),
        });
      }
    }

    let transcriptText = '';
    let transcriptSegments: TikTokTranscriptSegment[] | undefined = undefined;
    let transcriptSource: 'closed_captions' | 'audio_whisper' | 'video_description' = 'video_description';

    if (subtitles.length > 0) {
      const bestTrack =
        subtitles.find(s => s.langCode.startsWith('ar') || s.lang.includes('العربية')) ||
        subtitles.find(s => s.langCode.startsWith('en') || s.lang.includes('English')) ||
        subtitles.find(s => s.isAutoGenerated) ||
        subtitles[0];

      if (bestTrack?.url) {
        const subResult = await fetchAndParseSubtitles(bestTrack.url);
        if (subResult && subResult.text) {
          transcriptText = subResult.text;
          transcriptSegments = subResult.segments;
          transcriptSource = bestTrack.isAutoGenerated ? 'audio_whisper' : 'closed_captions';
          console.log(`[TikTokService] ✓ Extracted captions (${bestTrack.lang}): ${transcriptText.slice(0, 60)}...`);
        }
      }
    }

    if (!transcriptText) {
      transcriptText = desc;
      transcriptSource = 'video_description';
    }

    const durationSeconds = itemStruct?.video?.duration || itemStruct?.music?.duration || tikwm?.duration;
    const createTime = itemStruct?.createTime ? Number(itemStruct.createTime) : (tikwm?.create_time ? Number(tikwm.create_time) : undefined);

    const result: TikTokResult = {
      videoId,
      canonicalUrl,
      inputUrl: input,
      title: desc ? (desc.length > 80 ? desc.slice(0, 80) + '...' : desc) : `TikTok Video by @${author.username}`,
      description: desc,
      hashtags,
      author,
      stats,
      music,
      thumbnailUrl,
      dynamicCover,
      originCover,
      playUrl,
      subtitles,
      transcriptText,
      transcriptSegments,
      transcriptSource,
      durationSeconds,
      createTime,
      fetchedAt: Date.now(),
      cached: false,
    };

    setCached(canonicalUrl, result);
    setCached(videoId, result);
    console.log(`[TikTokService] ✓ Parsed @${author.username} (likes: ${stats.likes}, source: ${transcriptSource})`);

    return result;
  } catch (err: any) {
    console.error('[TikTokService Error]:', err);
    return {
      error: 'PARSE_ERROR',
      message: `تعذّر استخراج محتوى فيديو تيك توك: ${err?.message || 'خطأ غير معروف'}`,
      videoId,
    };
  }
}

// ─── AI Context Builder ───────────────────────────────────────────────────────

export function buildTikTokContextBlock(result: TikTokResult, maxChars = 10000): string {
  const bar = '━'.repeat(45);
  const uploadDate = result.createTime
    ? new Date(result.createTime * 1000).toLocaleDateString('ar-EG', { year: 'numeric', month: 'long', day: 'numeric' })
    : 'غير محدد';

  const statsStr = [
    result.stats.views ? `👁️ ${result.stats.views.toLocaleString('ar-EG')} مشاهدة` : '',
    result.stats.likes ? `❤️ ${result.stats.likes.toLocaleString('ar-EG')} إعجاب` : '',
    result.stats.comments ? `💬 ${result.stats.comments.toLocaleString('ar-EG')} تعليق` : '',
    result.stats.shares ? `🔄 ${result.stats.shares.toLocaleString('ar-EG')} مشاركة` : '',
    result.stats.saves ? `🔖 ${result.stats.saves.toLocaleString('ar-EG')} حفظ` : '',
  ].filter(Boolean).join(' | ') || 'إحصائيات غير معلنة';

  const truncatedText = (result.transcriptText || result.description).length > maxChars
    ? (result.transcriptText || result.description).slice(0, maxChars) + '\n[... تم اختصار النص لتناسب السياق ...]'
    : (result.transcriptText || result.description);

  return [
    '🎵 [بيانات واستخبارات فيديو تيك توك — مستخرج تلقائياً بدون تحميل ملفات]',
    bar,
    `• صانع المحتوى: ${result.author.nickname} (@${result.author.username})` + (result.author.verified ? ' [موثق ✅]' : ''),
    `• وصف الفيديو والوسوم: ${result.description || 'بدون وصف'}`,
    result.hashtags.length > 0 ? `• الهاشتاجات: ${result.hashtags.join(' ')}` : '',
    `• الصوت / الموسيقى: ${result.music.title} (بواسطة ${result.music.authorName})`,
    `• التفاعل والإحصائيات: ${statsStr}`,
    `• تاريخ النشر: ${uploadDate}`,
    `• الرابط المباشر: ${result.canonicalUrl}`,
    `• مصدر المحتوى والنص: ${result.transcriptSource === 'closed_captions' ? 'تفريغ الترجمة والتعرف الصوتي (Captions/ASR)' : 'الوصف والبيانات الوصفية للفيديو'}`,
    bar,
    '[محتوى الفيديو / الكلام المنطوق المستخرج]:',
    '',
    truncatedText,
    '',
    bar,
  ].filter(Boolean).join('\n');
}

// ─── TikTok User Profile & Recent Videos OSINT Engine ───────────────────────────

export interface TikTokUserPost {
  id: string;
  title: string;
  url: string;
  playUrl?: string;
  coverUrl?: string;
  createTime?: number;
  duration?: number;
  views?: number;
  likes?: number;
  comments?: number;
}

export interface TikTokUserProfileResult {
  success: boolean;
  username: string;
  nickname: string;
  avatarUrl?: string;
  bio?: string;
  verified?: boolean;
  followers?: number;
  following?: number;
  totalLikes?: number;
  videoCount?: number;
  recentVideos: TikTokUserPost[];
  latestVideo?: TikTokUserPost;
}

export async function fetchTikTokUserProfileAndVideos(username: string): Promise<TikTokUserProfileResult | null> {
  const cleanUsername = username.replace(/^@/, '').trim();
  if (!cleanUsername) return null;

  try {
    const res = await fetch(`https://www.tikwm.com/api/user/posts?unique_id=${encodeURIComponent(cleanUsername)}&count=12`, {
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
        'Accept': 'application/json',
      },
      signal: AbortSignal.timeout(4000)
    });

    if (res.ok) {
      const data = await res.json();
      if (data && data.code === 0 && data.data) {
        const videosRaw = Array.isArray(data.data.videos) ? data.data.videos : [];
        const recentVideos: TikTokUserPost[] = videosRaw.map((v: any) => ({
          id: String(v.video_id || v.id || ''),
          title: v.title || v.desc || 'فيديو بدون عنوان',
          url: `https://www.tiktok.com/@${cleanUsername}/video/${v.video_id || v.id}`,
          playUrl: v.play || v.wmplay,
          coverUrl: v.cover || v.origin_cover,
          createTime: v.create_time ? Number(v.create_time) : undefined,
          duration: v.duration,
          views: v.play_count,
          likes: v.digg_count,
          comments: v.comment_count,
        }));

        const latestVideo = recentVideos[0] || undefined;
        const author = data.data.author || {};

        return {
          success: true,
          username: cleanUsername,
          nickname: author.nickname || cleanUsername,
          avatarUrl: author.avatar,
          bio: author.signature || author.bio,
          verified: Boolean(author.verified),
          followers: author.follower_count,
          following: author.following_count,
          totalLikes: author.heart_count,
          videoCount: author.video_count,
          recentVideos,
          latestVideo,
        };
      }
    }
  } catch (err) {
    console.warn(`[TikTok OSINT] Failed to fetch profile for @${cleanUsername}:`, err);
  }

  return null;
}

export function buildTikTokProfileContextBlock(profile: TikTokUserProfileResult): string {
  const bar = '━'.repeat(45);
  const lines: string[] = [
    `🎵 [استخبارات حساب صانع المحتوى على تيك توك: @${profile.username}]`,
    bar,
    `• الاسم التعريفي: ${profile.nickname} (@${profile.username})` + (profile.verified ? ' [موثق ✅]' : ''),
    profile.bio ? `• النبذة التعريفية (Bio): ${profile.bio}` : '',
    profile.followers ? `• المتابعون: ${profile.followers.toLocaleString('ar-EG')}` : '',
    profile.totalLikes ? `• إجمالي الإعجابات: ${profile.totalLikes.toLocaleString('ar-EG')}` : '',
    bar,
  ];

  if (profile.latestVideo) {
    const latestDate = profile.latestVideo.createTime
      ? new Date(profile.latestVideo.createTime * 1000).toLocaleDateString('ar-EG', { year: 'numeric', month: 'long', day: 'numeric' })
      : 'حديثاً';
    lines.push(
      '🌟 [أحدث فيديو تم نشره بواسطة الحساب (Latest Video)]:',
      `• عنوان/وصف أحدث فيديو: ${profile.latestVideo.title}`,
      `• رابط أحدث فيديو: ${profile.latestVideo.url}`,
      `• تاريخ النشر: ${latestDate}`,
      profile.latestVideo.views ? `• المشاهدات: ${profile.latestVideo.views.toLocaleString('ar-EG')}` : '',
      profile.latestVideo.likes ? `• الإعجابات: ${profile.latestVideo.likes.toLocaleString('ar-EG')}` : '',
      bar
    );
  }

  if (profile.recentVideos.length > 1) {
    lines.push('📹 [قائمة الفيديوهات السابقة والحديثة للحساب]:');
    profile.recentVideos.slice(0, 5).forEach((v, idx) => {
      lines.push(`${idx + 1}. "${v.title}" — الرابط: ${v.url} (${v.views ? `${v.views} مشاهدة` : ''})`);
    });
    lines.push(bar);
  }

  return lines.filter(Boolean).join('\n');
}
