/**
 * YouTube Speech Intelligence Engine (Smart YouTuber Transcript & Monologue Analyzer)
 * -----------------------------------------------------------------------------------
 * Capabilities:
 *   - Extracts exact spoken words/monologue of YouTubers (Manual + Auto-Generated ASR)
 *   - Zero-failure multi-strategy retrieval (Direct InnerTube Scraping + youtube-transcript library)
 *   - Auto-fetches dual tracks: Original Spoken Audio Language + Arabic Auto-Translation
 *   - Intelligent Speech Normalization (filters audio noise: [Music], [♪♪♪], [Applause], [ضحك])
 *   - Timeline Paragraph Grouping (organizes speech into timestamped chunks: [01:20 - 02:15])
 *   - In-memory cache with 30-minute TTL
 */

import { YoutubeTranscript } from 'youtube-transcript';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface TranscriptSegment {
  text: string;
  offset: number;   // milliseconds from start
  duration: number; // milliseconds
  lang?: string;
}

export interface TimestampedBlock {
  timeRange: string;  // e.g. "01:20 - 02:05"
  startSeconds: number;
  endSeconds: number;
  speechText: string;
}

export interface YouTubeTranscriptResult {
  videoId: string;
  videoUrl: string;
  thumbnailUrl: string;
  title?: string;
  channelName?: string;
  durationSeconds?: number;
  language: string;
  isAutoGenerated: boolean;
  rawSpokenText: string;              // Continuous cleaned speech text
  arabicTranslationText?: string;     // Arabic translated text (if original not Arabic)
  timestampedBlocks: TimestampedBlock[]; // Grouped paragraphs with timecodes
  segments: TranscriptSegment[];
  wordCount: number;
  charCount: number;
  fetchedAt: number;
  cached?: boolean;
}

export type TranscriptError =
  | 'INVALID_URL'
  | 'TRANSCRIPT_DISABLED'
  | 'VIDEO_UNAVAILABLE'
  | 'NO_LANGUAGE'
  | 'RATE_LIMITED'
  | 'NETWORK_ERROR'
  | 'UNKNOWN';

export interface TranscriptFailure {
  error: TranscriptError;
  message: string;
  videoId?: string;
}

// ─── In-Memory Cache (30 min TTL) ─────────────────────────────────────────────

const CACHE_TTL_MS = 30 * 60 * 1000;
interface CacheEntry { result: YouTubeTranscriptResult; expiresAt: number; }
const transcriptCache = new Map<string, CacheEntry>();

function getCached(videoId: string): YouTubeTranscriptResult | null {
  const entry = transcriptCache.get(videoId);
  if (!entry || Date.now() > entry.expiresAt) {
    transcriptCache.delete(videoId);
    return null;
  }
  return { ...entry.result, cached: true };
}

function setCached(videoId: string, result: YouTubeTranscriptResult): void {
  transcriptCache.set(videoId, { result, expiresAt: Date.now() + CACHE_TTL_MS });
}

// ─── Video ID Extraction ───────────────────────────────────────────────────────

const YT_ID_REGEX = /^[a-zA-Z0-9_-]{11}$/;

export function extractYouTubeVideoId(input: string): string | null {
  if (!input || typeof input !== 'string') return null;
  const trimmed = input.trim();
  if (YT_ID_REGEX.test(trimmed)) return trimmed;

  try {
    const url = new URL(trimmed.startsWith('http') ? trimmed : `https://${trimmed}`);
    const host = url.hostname.replace(/^m\./, '').replace(/^www\./, '');

    if (host === 'youtube.com' || host === 'youtube-nocookie.com') {
      const v = url.searchParams.get('v');
      if (v && YT_ID_REGEX.test(v)) return v;
      const pathMatch = url.pathname.match(/^\/(?:shorts|embed|live|v|e)\/([a-zA-Z0-9_-]{11})/);
      if (pathMatch?.[1]) return pathMatch[1];
    }

    if (host === 'youtu.be') {
      const pathId = url.pathname.replace(/^\//, '').split('?')[0].split('/')[0];
      if (YT_ID_REGEX.test(pathId)) return pathId;
    }
  } catch {
    const fallback = trimmed.match(/(?:v=|youtu\.be\/|\/(?:shorts|embed|live|v|e)\/)([a-zA-Z0-9_-]{11})/);
    if (fallback?.[1]) return fallback[1];
  }
  return null;
}

export function containsYouTubeUrl(text: string): boolean {
  return /(?:youtube\.com|youtu\.be)\//i.test(text);
}

export function extractYouTubeUrlFromText(text: string): string | null {
  if (!text) return null;
  const m = text.match(/https?:\/\/(?:www\.|m\.)?(?:youtube\.com|youtu\.be)\/[^\s<>"']+/i);
  if (m) return m[0];
  const s = text.match(/(?:^|\s)(youtu\.be\/[^\s<>"']+)/i);
  if (s) return 'https://' + s[1].trim();
  return null;
}

interface OEmbedMeta { title?: string; author_name?: string; thumbnail_url?: string; description?: string; }

async function fetchVideoMeta(videoId: string): Promise<OEmbedMeta> {
  // 1. YouTube official oEmbed (watch)
  try {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 3500);
    const res = await fetch(
      `https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=${videoId}&format=json`,
      { headers: { 'User-Agent': 'Mozilla/5.0' }, signal: controller.signal }
    );
    clearTimeout(timer);
    if (res.ok) {
      const data = await res.json() as OEmbedMeta;
      if (data.title) return data;
    }
  } catch {}

  // 2. YouTube official oEmbed (shorts)
  try {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 3500);
    const res = await fetch(
      `https://www.youtube.com/oembed?url=https://www.youtube.com/shorts/${videoId}&format=json`,
      { headers: { 'User-Agent': 'Mozilla/5.0' }, signal: controller.signal }
    );
    clearTimeout(timer);
    if (res.ok) {
      const data = await res.json() as OEmbedMeta;
      if (data.title) return data;
    }
  } catch {}

  // 3. noembed fallback
  try {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 3500);
    const res = await fetch(
      `https://noembed.com/embed?url=https://www.youtube.com/watch?v=${videoId}`,
      { signal: controller.signal }
    );
    clearTimeout(timer);
    if (res.ok) {
      const data = await res.json();
      if (data && data.title && !data.error) {
        return {
          title: data.title,
          author_name: data.author_name,
          thumbnail_url: data.thumbnail_url
        };
      }
    }
  } catch {}

  // 4. Direct HTML meta tag scraping (for Shorts, mobile & age-gated embeds)
  for (const pageUrl of [`https://www.youtube.com/watch?v=${videoId}`, `https://www.youtube.com/shorts/${videoId}`]) {
    try {
      const controller = new AbortController();
      const timer = setTimeout(() => controller.abort(), 4000);
      const res = await fetch(pageUrl, {
        signal: controller.signal,
        headers: {
          'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
          'Accept-Language': 'ar,en-US;q=0.9,en;q=0.8'
        }
      });
      clearTimeout(timer);
      if (res.ok) {
        const html = await res.text();
        const ogTitle = html.match(/<meta\s+property=["']og:title["']\s+content=["'](.*?)["']/i)?.[1]
          || html.match(/<title>(.*?)<\/title>/i)?.[1]?.replace(/\s*-\s*YouTube$/i, '');
        const ogDesc = html.match(/<meta\s+property=["']og:description["']\s+content=["'](.*?)["']/i)?.[1];
        const author = html.match(/<link\s+itemprop=["']name["']\s+content=["'](.*?)["']/i)?.[1]
          || html.match(/"author":\s*"(.*?)"/i)?.[1]
          || html.match(/"ownerChannelName":\s*"(.*?)"/i)?.[1];
        const thumb = html.match(/<meta\s+property=["']og:image["']\s+content=["'](.*?)["']/i)?.[1]
          || `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`;

        if (ogTitle && !ogTitle.includes('- YouTube')) {
          return {
            title: ogTitle,
            author_name: author,
            description: ogDesc,
            thumbnail_url: thumb
          };
        }
      }
    } catch {}
  }

  return {
    thumbnail_url: `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`
  };
}

// ─── Speech Normalizer & Cleaner ──────────────────────────────────────────────

/**
 * Cleans non-speech audio cues, music indicators, HTML entities, and formatting artifacts
 */
export function cleanSpokenText(raw: string): string {
  if (!raw) return '';
  return raw
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&#39;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/&nbsp;/g, ' ')
    .replace(/<[^>]+>/g, '')
    // Remove music notes and symbols
    .replace(/[♪♫#♬♩]/g, '')
    .replace(/\[\s*(?:music|applause|laughter|screaming|cheering|coughing|silence|snicker|sigh|giggle|gasp|sighs|cries|singing|chuckle|inaudible|موسيقى|تصفيق|ضحك|صمت|تنفس|صراخ|بكاء|أغنية)\s*\]/gi, '')
    .replace(/\(\s*(?:music|applause|laughter|cheering|singing|موسيقى|تصفيق|ضحك)\s*\)/gi, '')
    .replace(/^>>\s*/g, '')
    .replace(/\r?\n+/g, ' ')
    .replace(/\s{2,}/g, ' ')
    .trim();
}

/**
 * Formats seconds into MM:SS or HH:MM:SS
 */
function formatTime(seconds: number): string {
  const h = Math.floor(seconds / 3600);
  const m = Math.floor((seconds % 3600) / 60);
  const s = Math.floor(seconds % 60);
  if (h > 0) {
    return `${h}:${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`;
  }
  return `${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`;
}

/**
 * Groups continuous transcript segments into natural timestamped speech paragraphs (every ~30-45 seconds or ~50-80 words)
 */
function buildTimestampedBlocks(segments: TranscriptSegment[], intervalSeconds = 45): TimestampedBlock[] {
  if (!segments || segments.length === 0) return [];

  const blocks: TimestampedBlock[] = [];
  let currentWords: string[] = [];
  let blockStartSec = Math.floor((segments[0].offset || 0) / 1000);
  let blockEndSec = blockStartSec;

  for (let i = 0; i < segments.length; i++) {
    const seg = segments[i];
    const segText = cleanSpokenText(seg.text);
    if (!segText) continue;

    const segStartSec = Math.floor((seg.offset || 0) / 1000);
    const segDurSec = Math.ceil((seg.duration || 0) / 1000);
    blockEndSec = segStartSec + segDurSec;

    currentWords.push(segText);

    const isTimeThreshold = (blockEndSec - blockStartSec) >= intervalSeconds;
    const isWordCountThreshold = currentWords.join(' ').split(/\s+/).length >= 75;
    const isLast = (i === segments.length - 1);

    if ((isTimeThreshold || isWordCountThreshold || isLast) && currentWords.length > 0) {
      blocks.push({
        timeRange: `${formatTime(blockStartSec)} - ${formatTime(blockEndSec)}`,
        startSeconds: blockStartSec,
        endSeconds: blockEndSec,
        speechText: currentWords.join(' ').replace(/\s{2,}/g, ' ').trim()
      });
      currentWords = [];
      if (i + 1 < segments.length) {
        blockStartSec = Math.floor((segments[i + 1].offset || 0) / 1000);
      }
    }
  }

  return blocks;
}

// ─── Direct YouTube Web Page & Caption Track Parser (Strategy 1) ──────────────

interface DirectScrapedCaptions {
  segments: TranscriptSegment[];
  language: string;
  isAutoGenerated: boolean;
  arabicTranslationText?: string;
}

async function scrapeCaptionsDirectly(videoId: string): Promise<DirectScrapedCaptions | null> {
  try {
    const videoUrl = `https://www.youtube.com/watch?v=${videoId}`;
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 6000);

    const res = await fetch(videoUrl, {
      signal: controller.signal,
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36',
        'Accept-Language': 'ar,en-US;q=0.9,en;q=0.8',
      }
    });
    clearTimeout(timer);

    if (!res.ok) return null;
    const html = await res.text();

    const match = html.match(/ytInitialPlayerResponse\s*=\s*(\{.+?\});/s);
    if (!match) return null;

    const playerData = JSON.parse(match[1]);
    const captionTracks = playerData?.captions?.playerCaptionsTracklistRenderer?.captionTracks;

    if (!Array.isArray(captionTracks) || captionTracks.length === 0) {
      return null;
    }

    // Language priority:
    // 1. Manual Arabic
    // 2. Auto-generated Arabic (ASR)
    // 3. Manual English
    // 4. Auto-generated English
    // 5. Any available track
    let chosenTrack =
      captionTracks.find((t: any) => t.languageCode === 'ar' && t.kind !== 'asr') ||
      captionTracks.find((t: any) => (t.languageCode === 'ar' || t.languageCode?.startsWith('ar'))) ||
      captionTracks.find((t: any) => t.languageCode === 'en' && t.kind !== 'asr') ||
      captionTracks.find((t: any) => t.languageCode === 'en' || t.languageCode?.startsWith('en')) ||
      captionTracks[0];

    if (!chosenTrack || !chosenTrack.baseUrl) return null;

    const isAuto = chosenTrack.kind === 'asr';
    const lang = chosenTrack.languageCode || 'unknown';

    // Fetch the track XML
    const trackRes = await fetch(chosenTrack.baseUrl);
    if (!trackRes.ok) return null;
    const xml = await trackRes.text();

    const segments: TranscriptSegment[] = [];
    const xmlRegex = /<text start="([\d.]+)" dur="([\d.]+)"[^>]*>([\s\S]*?)<\/text>/g;
    let m: RegExpExecArray | null;

    while ((m = xmlRegex.exec(xml)) !== null) {
      const startSec = parseFloat(m[1]);
      const durSec = parseFloat(m[2]);
      const clean = cleanSpokenText(m[3]);
      if (clean) {
        segments.push({
          text: clean,
          offset: Math.round(startSec * 1000),
          duration: Math.round(durSec * 1000),
          lang: lang,
        });
      }
    }

    if (segments.length === 0) return null;

    // If original speech is not Arabic, attempt fetching the Arabic auto-translate track
    let arabicTranslationText = '';
    if (lang !== 'ar' && !lang.startsWith('ar')) {
      try {
        const arUrl = chosenTrack.baseUrl + '&tlang=ar';
        const arRes = await fetch(arUrl);
        if (arRes.ok) {
          const arXml = await arRes.text();
          const arTexts: string[] = [];
          let mAr: RegExpExecArray | null;
          const reAr = /<text start="([\d.]+)" dur="([\d.]+)"[^>]*>([\s\S]*?)<\/text>/g;
          while ((mAr = reAr.exec(arXml)) !== null) {
            const cleanAr = cleanSpokenText(mAr[3]);
            if (cleanAr) arTexts.push(cleanAr);
          }
          if (arTexts.length > 0) {
            arabicTranslationText = arTexts.join(' ').replace(/\s{2,}/g, ' ').trim();
          }
        }
      } catch {
        // Translation is optional enhancement
      }
    }

    return {
      segments,
      language: lang,
      isAutoGenerated: isAuto,
      arabicTranslationText: arabicTranslationText || undefined,
    };
  } catch {
    return null;
  }
}

// ─── Secondary Fallback (youtube-transcript library) ───────────────────────────

const PREFERRED_LANGS = ['ar', 'en', 'en-US', 'en-GB'];

async function tryFetchTranscriptLib(
  videoId: string,
  langs: string[]
): Promise<{ segments: TranscriptSegment[]; lang: string } | null> {
  for (const lang of langs) {
    try {
      const raw = await YoutubeTranscript.fetchTranscript(videoId, { lang });
      if (raw && raw.length > 0) {
        return {
          segments: raw.map((s: any) => ({
            text: cleanSpokenText(s.text),
            offset: s.offset,
            duration: s.duration,
            lang: s.lang || lang,
          })).filter((s: any) => Boolean(s.text)),
          lang,
        };
      }
    } catch (err: any) {
      const msg = (err?.message || '').toLowerCase();
      if (msg.includes('no transcript') || msg.includes('not available') || msg.includes('language')) continue;
      throw err;
    }
  }
  return null;
}

// ─── Master Pipeline: fetchYouTubeTranscript ──────────────────────────────────

export async function fetchYouTubeTranscript(
  input: string
): Promise<YouTubeTranscriptResult | TranscriptFailure> {
  const videoId = extractYouTubeVideoId(input);
  if (!videoId) {
    return { error: 'INVALID_URL', message: `لم يتم التعرف على رابط يوتيوب: "${input}"` };
  }

  // 1. Cache hit
  const cached = getCached(videoId);
  if (cached) {
    console.log(`[YouTubeTranscript] Cache hit for videoId: ${videoId}`);
    return cached;
  }

  // 2. Fetch oEmbed metadata and speech transcript concurrently
  let meta: OEmbedMeta = {};
  let speechData: {
    segments: TranscriptSegment[];
    language: string;
    isAutoGenerated: boolean;
    arabicTranslationText?: string;
  } | null = null;

  try {
    const [metaResult, scrapedDirect] = await Promise.all([
      fetchVideoMeta(videoId),
      scrapeCaptionsDirectly(videoId)
    ]);

    meta = metaResult || {};

    if (scrapedDirect && scrapedDirect.segments.length > 0) {
      speechData = scrapedDirect;
      console.log(`[YouTubeTranscript] Direct scraping succeeded: ${scrapedDirect.segments.length} segments (${scrapedDirect.language}, asr=${scrapedDirect.isAutoGenerated})`);
    } else {
      // Fallback to youtube-transcript library
      console.log(`[YouTubeTranscript] Direct scraping missed, falling back to library for: ${videoId}`);
      let libResult = await tryFetchTranscriptLib(videoId, PREFERRED_LANGS);
      if (!libResult) {
        const raw = await YoutubeTranscript.fetchTranscript(videoId);
        if (raw && raw.length > 0) {
          libResult = {
            segments: raw.map((s: any) => ({
              text: cleanSpokenText(s.text),
              offset: s.offset,
              duration: s.duration,
              lang: s.lang || 'auto',
            })).filter((s: any) => Boolean(s.text)),
            lang: raw[0]?.lang || 'auto',
          };
        }
      }

      if (libResult && libResult.segments.length > 0) {
        speechData = {
          segments: libResult.segments,
          language: libResult.lang,
          isAutoGenerated: false,
        };
      }
    }
  } catch (err: any) {
    console.warn(`[YouTubeTranscript Exception for ${videoId}]:`, err?.message || err);
  }

  if (!speechData || speechData.segments.length === 0) {
    const title = meta?.title || 'فيديو يوتيوب';
    const channelName = meta?.author_name || 'صانع المحتوى';
    const fallbackDesc = meta?.description || '';
    const fallbackResult: YouTubeTranscriptResult = {
      videoId,
      videoUrl: `https://www.youtube.com/watch?v=${videoId}`,
      thumbnailUrl: meta?.thumbnail_url || `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`,
      title,
      channelName,
      durationSeconds: undefined,
      language: 'ar',
      isAutoGenerated: false,
      rawSpokenText: fallbackDesc,
      arabicTranslationText: undefined,
      timestampedBlocks: fallbackDesc ? [{
        timeRange: '00:00 - 01:00',
        startSeconds: 0,
        endSeconds: 60,
        speechText: fallbackDesc
      }] : [],
      segments: [],
      wordCount: fallbackDesc.split(/\s+/).filter(Boolean).length,
      charCount: fallbackDesc.length,
      fetchedAt: Date.now(),
      cached: false,
    };
    return fallbackResult;
  }

  // 3. Build continuous clean spoken text and timestamped blocks
  const rawSpokenText = speechData.segments
    .map(s => s.text)
    .join(' ')
    .replace(/\s{2,}/g, ' ')
    .trim();

  const timestampedBlocks = buildTimestampedBlocks(speechData.segments);

  const lastSeg = speechData.segments[speechData.segments.length - 1];
  const durationSeconds = lastSeg ? Math.round((lastSeg.offset + lastSeg.duration) / 1000) : undefined;

  const result: YouTubeTranscriptResult = {
    videoId,
    videoUrl: `https://www.youtube.com/watch?v=${videoId}`,
    thumbnailUrl: meta?.thumbnail_url || `https://img.youtube.com/vi/${videoId}/hqdefault.jpg`,
    title: meta?.title,
    channelName: meta?.author_name,
    durationSeconds,
    language: speechData.language,
    isAutoGenerated: speechData.isAutoGenerated,
    rawSpokenText,
    arabicTranslationText: speechData.arabicTranslationText,
    timestampedBlocks,
    segments: speechData.segments,
    wordCount: rawSpokenText.split(/\s+/).filter(Boolean).length,
    charCount: rawSpokenText.length,
    fetchedAt: Date.now(),
    cached: false,
  };

  setCached(videoId, result);
  console.log(`[YouTubeSpeech] ✓ Extracted ${result.wordCount} spoken words (${result.language}, ${timestampedBlocks.length} timeline blocks) for: "${result.title || videoId}"`);
  return result;
}

// ─── Smart AI Context Builder ─────────────────────────────────────────────────

/**
 * Builds a highly structured, intelligent speech context block with timeline timestamps,
 * allowing the AI to quote the YouTuber with precision.
 */
export function buildTranscriptContextBlock(
  result: YouTubeTranscriptResult,
  maxChars = 14000
): string {
  const durationStr = result.durationSeconds
    ? `${Math.floor(result.durationSeconds / 60)} دقيقة و ${result.durationSeconds % 60} ثانية`
    : 'غير محددة';

  const bar = '━'.repeat(45);

  // Format timestamped monologue blocks
  const timelineText = result.timestampedBlocks
    .map(b => `⏱️ [${b.timeRange}] ${b.speechText}`)
    .join('\n\n');

  let speechSection = '';
  if (timelineText.length <= maxChars) {
    speechSection = timelineText;
  } else {
    // Truncate cleanly at block boundaries
    let current = '';
    for (const b of result.timestampedBlocks) {
      const line = `⏱️ [${b.timeRange}] ${b.speechText}\n\n`;
      if ((current + line).length > maxChars) break;
      current += line;
    }
    speechSection = (current || timelineText.slice(0, maxChars)) + '\n[... تم اقتصار العرض على أبرز المحتوى لتناسب سياق الـ AI ...]';
  }

  // Include Arabic translation summary if present
  let arabicTransSection = '';
  if (result.arabicTranslationText && result.language !== 'ar' && !result.language.startsWith('ar')) {
    const arTruncated = result.arabicTranslationText.length > 3000
      ? result.arabicTranslationText.slice(0, 3000) + '...'
      : result.arabicTranslationText;
    arabicTransSection = `\n\n[الترجمة العربية الفورية للكلام المنطوق]:\n${arTruncated}\n`;
  }

  return [
    '[تفريغ الكلام المنطوق الحقيقي لليوتيوبر / المتحدث داخل الفيديو — مستخرج بالطوابع الزمنية]',
    bar,
    `• عنوان الفيديو: ${result.title || 'غير معروف'}`,
    `• القناة / صانع المحتوى: ${result.channelName || 'غير معروفة'}`,
    `• رابط الفيديو المباشر: ${result.videoUrl}`,
    `• لغة الكلام الأصلية: ${result.language} (${result.isAutoGenerated ? 'تعرف صوتي تلقائي ASR' : 'نص أصلي مدقق'})`,
    `• مدة الفيديو الإجمالية: ${durationStr}`,
    `• إجمالي الكلمات المنطوقة: ${result.wordCount.toLocaleString('ar-EG')} كلمة`,
    bar,
    '[كلام اليوتيوبر المسجل موزّعاً حسب الطوابع الزمنية للفيديو]:',
    '',
    speechSection,
    arabicTransSection,
    bar,
    '[توجيه ذكي لتحليل كلام اليوتيوبر]:',
    '1. استخدم الطوابع الزمنية [MM:SS] لتوثيق اللحظة التي ذكر فيها اليوتيوبر كل معلومة أو نصيحة في ردك.',
    '2. اقتبس عبارات المتحدث الجوهرية ولخص أفكاره وتسلسل حديثه باللغة العربية الفصحى بدقة واحترافية.',
    bar
  ].filter(Boolean).join('\n');
}
